name: 'Auto Rebase PRs'
description: 'Automatic rebasing when a base branch changes, for efficient PR flows'
branding:
  icon: git-pull-request
  color: green
inputs:
  github_token:
    description: Token for the GitHub API.
    required: true
  filter:
    description: Filter to be used. 'auto-merge' | 'always'
    required: false
    default: 'auto-merge'
  max_mergeable_rebases:
    description: >
      If one more of the PRs have their review approval and no vailed CI
      checks, how many of such PRs should be rebased. The motivation is
      that some repos could see an explosion of jobs if this action is
      capable of re-triggering itself after the rebased PRs are merged.
    required: false
    default: '0'
runs:
  using: 'node16'
  main: 'dist/index.js'
